"""bosqich 5

Revision ID: 24a1237ca0fc
Revises: 08cfb3227b11
Create Date: 2026-08-09 09:50:31.632279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0002_bosqich_5'
down_revision: Union[str, Sequence[str], None] = '08cfb3227b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'extracting', 'generating', 'ready', 'failed', name='material_status_enum'), nullable=False),
    sa.Column('extracted_text_length', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_deleted_at'), 'materials', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_materials_student_profile_id'), 'materials', ['student_profile_id'], unique=False)
    op.create_table('generated_quizzes',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='quiz_difficulty_enum'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_quizzes_deleted_at'), 'generated_quizzes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generated_quizzes_material_id'), 'generated_quizzes', ['material_id'], unique=False)
    op.create_index(op.f('ix_generated_quizzes_student_profile_id'), 'generated_quizzes', ['student_profile_id'], unique=False)
    op.create_table('material_chunks',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chunks_deleted_at'), 'material_chunks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_material_chunks_material_id'), 'material_chunks', ['material_id'], unique=False)
    op.create_table('generated_questions',
    sa.Column('generated_quiz_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=1024), nullable=False),
    sa.Column('option_b', sa.String(length=1024), nullable=False),
    sa.Column('option_c', sa.String(length=1024), nullable=False),
    sa.Column('option_d', sa.String(length=1024), nullable=False),
    sa.Column('correct_option', postgresql.ENUM('A', 'B', 'C', 'D', name='correct_option_enum', create_type=False), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generated_quiz_id'], ['generated_quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_questions_deleted_at'), 'generated_questions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generated_questions_generated_quiz_id'), 'generated_questions', ['generated_quiz_id'], unique=False)
    op.create_table('generated_quiz_attempts',
    sa.Column('generated_quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generated_quiz_id'], ['generated_quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_quiz_attempts_deleted_at'), 'generated_quiz_attempts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_generated_quiz_attempts_generated_quiz_id'), 'generated_quiz_attempts', ['generated_quiz_id'], unique=False)
    op.create_index(op.f('ix_generated_quiz_attempts_student_profile_id'), 'generated_quiz_attempts', ['student_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_quiz_attempts_student_profile_id'), table_name='generated_quiz_attempts')
    op.drop_index(op.f('ix_generated_quiz_attempts_generated_quiz_id'), table_name='generated_quiz_attempts')
    op.drop_index(op.f('ix_generated_quiz_attempts_deleted_at'), table_name='generated_quiz_attempts')
    op.drop_table('generated_quiz_attempts')
    op.drop_index(op.f('ix_generated_questions_generated_quiz_id'), table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_deleted_at'), table_name='generated_questions')
    op.drop_table('generated_questions')
    op.drop_index(op.f('ix_material_chunks_material_id'), table_name='material_chunks')
    op.drop_index(op.f('ix_material_chunks_deleted_at'), table_name='material_chunks')
    op.drop_table('material_chunks')
    op.drop_index(op.f('ix_generated_quizzes_student_profile_id'), table_name='generated_quizzes')
    op.drop_index(op.f('ix_generated_quizzes_material_id'), table_name='generated_quizzes')
    op.drop_index(op.f('ix_generated_quizzes_deleted_at'), table_name='generated_quizzes')
    op.drop_table('generated_quizzes')
    op.drop_index(op.f('ix_materials_student_profile_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_deleted_at'), table_name='materials')
    op.drop_table('materials')
    postgresql.ENUM(name='quiz_difficulty_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='material_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
