"""add_modules_time_limits_points

Revision ID: a93d80a9d75d
Revises: efd06fe1e49d
Create Date: 2026-07-04 02:14:55.559355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93d80a9d75d'
down_revision: Union[str, Sequence[str], None] = 'efd06fe1e49d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("TIMEZONE('Asia/Tashkent', now())"), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_deleted_at'), 'modules', ['deleted_at'], unique=False)
    op.add_column('quiz_attempts', sa.Column('time_taken_seconds', sa.Integer(), nullable=False))
    op.add_column('quizzes', sa.Column('time_limit_seconds', sa.Integer(), nullable=False))
    op.add_column('topics', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topics', 'modules', ['module_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'module_id')
    op.drop_column('quizzes', 'time_limit_seconds')
    op.drop_column('quiz_attempts', 'time_taken_seconds')
    op.drop_index(op.f('ix_modules_deleted_at'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
